### ISSUE TITLE
Send plots and statistics to me

### ISSUE THREAD

**Issue by mrtommyb** [barentsen/kpub#1]
@barentsen could you send me some plots and statistics for the publications broken down by Kepler/K2 and exoplanets/astrophysics. HQ want this by tomorrow

**Comment by barentsen** [comment]
Done.

**Comment by mrtommyb** [comment]
Do you have pushable code for making the plots?

**Comment by barentsen** [comment]
Ok, the `kpub-plot` command has now been added which creates the plot.
